// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frwnfukydjwilfobxxhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyd25mdWt5ZGp3aWxmb2J4eGh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MzgzNzMsImV4cCI6MjA2NzUxNDM3M30.Y23_ubZv3t8_GgflX2QfqRyFpu6Lc5ef7xS8I_stEyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});